version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: facturador_db
      MYSQL_USER: facturador_user
      MYSQL_PASSWORD: facturador_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - django_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    entrypoint: ./compose/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: facturador.settings
      DB_NAME: facturador_db
      DB_USER: facturador_user
      DB_PASSWORD: facturador_password
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  db_data:
